---
- hosts: appservers
  user: bunnies
  sudo: yes
  tasks:

    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=yes
      notify:
        - start nginx

    - name: install common packages needed for python
      action: apt pkg={{ item }} state=installed update_cache=yes
      with_items:
        - build-essential
        - libpq-dev
        - libxml2-dev
        - libjpeg62
        - libjpeg62-dev
        - libreadline6-dev
        - libfreetype6
        - libfreetype6-dev
        - libgdbm-dev
        - libbz2-dev
        - zlib1g-dev
        - git-core

    - name: remove default nginx site
      action: file path=/etc/nginx/sites-enabled/default state=absent

    - name: write nginx.conf
      action: template src=templates/nginx.conf dest=/etc/nginx/nginx.conf

    - name: create supervisord config folder
      action: file dest=/etc/supervisor state=directory owner=root

    - name: create supervisord config
      action: template src=templates/supervisord.conf dest=/etc/supervisord.conf

    - name: create supervisord init script
      action: template src=templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

    - name: start supervisord service and have it run during system startup
      action: service name=supervisord state=started enabled=yes

    - name: create webapps directory
      action: file dest=/srv/webapps state=directory
    
  handlers:
    - name: start nginx
      service: name=nginx state=started
